services:
  redis-stack:
    #image: redis/redis-stack:latest
    image: docker.1ms.run/redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass redis-stack-password-for-agentic-soc-platform
    volumes:
      - ./redis-data:/data